# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # raiz do projeto (onde está o .github/workflows)
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
